name: Test deployment

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - '.github/**'

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn
          cache-dependency-path: ./yarn.lock
      - name: Test build
        run: |
          yarn install --frozen-lockfile
          yarn build
